version: '3'
services:
  db:
    image: postgres:9.6-alpine
  app:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/opt/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
