default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/data/development.sqlite3
test:
  <<: *default
  database: db/data/test.sqlite3

production:
  <<: *default
  database: db/data/production.sqlite3


# development:
#   adapter: sqlite3
#   host: localhost
#   encoding: unicode
#   database: BikeRental_dev
#   pool: 5

# test:
#   adapter: sqlite3
#   encoding: unicode
#   database: BikeRental_test
#   pool: 5

# # Add the below...

# production:
#   adapter: postgresql
#   host: localhost
#   encoding: unicode
#   database: BikeRental_production
#   pool: 5
#   username:
#   password:
